-- OSG Financial Posting Workflow proof v0.2
-- Aligned with current pre-v1 schema. DEV proof only.
-- UUIDv7 IDs for DomainEvent/Outbox are generated by application and passed in.

create or replace function osg_post_economic_event_v02(
  p_organization_id uuid,
  p_event_id uuid,
  p_actor_user_id uuid,
  p_domain_event_id uuid,
  p_outbox_id uuid
)
returns void
language plpgsql
as $$
declare
  v_status text;
  v_amount numeric(14,2);
  v_allocated numeric(14,2);
  v_property_id uuid;
  v_economic_date date;
  v_financial_period_id uuid;
  v_allocation_count integer;
begin
  -- 1. Lock aggregate root in tenant scope.
  select status,amount,property_id,economic_date,financial_period_id
    into v_status,v_amount,v_property_id,v_economic_date,v_financial_period_id
  from economic_event
  where organization_id=p_organization_id and id=p_event_id
  for update;

  if not found then
    raise exception 'ECONOMIC_EVENT_NOT_FOUND';
  end if;

  if v_status not in ('DRAFT','REVIEWED') then
    raise exception 'ECONOMIC_EVENT_INVALID_STATE';
  end if;

  -- 2. Lock current Allocation set and compute conservation.
  perform 1
  from allocation
  where organization_id=p_organization_id
    and economic_event_id=p_event_id
  order by id
  for update;

  select coalesce(sum(amount),0),count(*)
    into v_allocated,v_allocation_count
  from allocation
  where organization_id=p_organization_id
    and economic_event_id=p_event_id;

  if round(v_allocated,2) <> round(v_amount,2) then
    raise exception 'OSG_ALLOCATION_NOT_BALANCED event=% expected=% actual=%',
      p_event_id,v_amount,v_allocated;
  end if;

  if v_allocation_count=0 and v_amount<>0 then
    raise exception 'OSG_ALLOCATION_REQUIRED';
  end if;

  -- 3. Ensure a valid period exists before final state transition.
  if v_financial_period_id is null then
    v_financial_period_id := osg_resolve_financial_period(
      p_organization_id,v_property_id,v_economic_date
    );

    update economic_event
      set financial_period_id=v_financial_period_id
    where organization_id=p_organization_id and id=p_event_id;
  end if;

  perform osg_assert_target_period_open_for_post(p_event_id);

  -- 4. Approval-policy evaluation is performed by application/domain layer before
  -- entering this function. DB approval artifacts remain auditable and permission
  -- checks are not delegated to this proof function.

  -- 5. Final state transition. Period/property/immutability triggers execute here.
  update economic_event
  set status='POSTED',
      posted_at=now(),
      posted_by_user_id=p_actor_user_id,
      row_version=row_version+1
  where organization_id=p_organization_id and id=p_event_id;

  -- Defense-in-depth after status transition; transaction rolls back on failure.
  perform osg_assert_economic_event_balanced(p_event_id);

  -- 6. Domain event written in same transaction as state.
  insert into domain_event (
    id,organization_id,property_id,event_type,event_version,
    aggregate_type,aggregate_id,aggregate_version,occurred_at,
    actor_type,actor_id,payload
  )
  select
    p_domain_event_id,
    ee.organization_id,
    ee.property_id,
    'EconomicEvent.Posted',
    1,
    'EconomicEvent',
    ee.id,
    ee.row_version,
    now(),
    'USER',
    p_actor_user_id,
    jsonb_build_object(
      'economic_event_id',ee.id,
      'event_type',ee.event_type,
      'effect_direction',ee.effect_direction,
      'economic_date',ee.economic_date,
      'amount',ee.amount,
      'currency',ee.currency,
      'financial_period_id',ee.financial_period_id,
      'allocation_count',v_allocation_count
    )
  from economic_event ee
  where ee.organization_id=p_organization_id and ee.id=p_event_id;

  -- 7. Outbox record guarantees post-commit delivery/retry.
  insert into outbox_event (
    id,organization_id,domain_event_id,status,available_at,attempts
  ) values (
    p_outbox_id,p_organization_id,p_domain_event_id,'PENDING',now(),0
  );
end;
$$;

-- REQUIRED caller workflow:
-- A. claim CommandIdempotency transactionally
-- B. authorize + approval-policy check
-- C. call osg_post_economic_event_v02 inside same business transaction
-- D. commit
-- E. persist/replay command response through idempotency ledger
--
-- Required P0 tests:
-- balanced success; imbalance rollback; HARD_CLOSED reject;
-- property-context mismatch reject; duplicate command single effect;
-- concurrent posting one accepted outcome; DomainEvent+Outbox atomicity.
