-- OSG PostgreSQL schema candidate v0.95 — CORE
-- PRE-FREEZE / DEV CANDIDATE. NOT A PRODUCTION MIGRATION.
-- Canonical IDs are UUIDv7 generated by the application (ADR-007).

create extension if not exists btree_gist;

-- ================================================================
-- TENANCY / IDENTITY
-- ================================================================

create table organization (
  id uuid primary key,
  name text not null,
  slug text not null unique,
  default_currency char(3) not null default 'PLN',
  default_timezone text not null default 'Europe/Warsaw',
  status text not null check (status in ('ACTIVE','SUSPENDED','ARCHIVED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  row_version bigint not null default 1
);

create table party (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  party_type text not null check (party_type in ('PERSON','COMPANY','PLATFORM','PUBLIC_BODY','OTHER')),
  display_name text not null,
  legal_name text,
  tax_id text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  row_version bigint not null default 1,
  unique (organization_id, id)
);

create table user_account (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  party_id uuid,
  email_login text not null,
  status text not null check (status in ('INVITED','ACTIVE','SUSPENDED','ARCHIVED')),
  mfa_enabled boolean not null default false,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  unique (organization_id, email_login),
  foreign key (organization_id, party_id) references party(organization_id, id)
);

create table role (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  code text not null,
  name text not null,
  active boolean not null default true,
  unique (organization_id, id),
  unique (organization_id, code)
);

create table permission (
  code text primary key,
  description text not null
);

create table role_permission (
  organization_id uuid not null references organization(id),
  role_id uuid not null,
  permission_code text not null references permission(code),
  primary key (role_id, permission_code),
  foreign key (organization_id, role_id) references role(organization_id, id)
);

-- ================================================================
-- PROPERTY / DIGITAL TWIN
-- ================================================================

create table property (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  name text not null,
  code text not null,
  property_type text not null default 'GLAMPING',
  timezone text not null default 'Europe/Warsaw',
  currency char(3) not null default 'PLN',
  status text not null check (status in ('DEVELOPMENT','ACTIVE','SEASONAL','CLOSED','ARCHIVED')),
  opened_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  row_version bigint not null default 1,
  unique (organization_id, id),
  unique (organization_id, code)
);

create table role_assignment (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  user_account_id uuid not null,
  role_id uuid not null,
  property_id uuid,
  created_at timestamptz not null default now(),
  archived_at timestamptz,
  unique (organization_id, id),
  foreign key (organization_id, user_account_id) references user_account(organization_id, id),
  foreign key (organization_id, role_id) references role(organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id)
);

create table zone (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  parent_zone_id uuid,
  name text not null,
  zone_type text,
  active boolean not null default true,
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, parent_zone_id) references zone(organization_id, id)
);

create table unit_type (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  name text not null,
  code text not null,
  base_capacity integer not null check (base_capacity > 0),
  max_capacity integer not null check (max_capacity >= base_capacity),
  area_m2 numeric(10,2),
  active boolean not null default true,
  unique (organization_id, id),
  unique (property_id, code),
  foreign key (organization_id, property_id) references property(organization_id, id)
);

create table unit (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  unit_type_id uuid not null,
  zone_id uuid,
  code text not null,
  name text not null,
  lifecycle_status text not null check (lifecycle_status in ('PLANNED','ACTIVE','OUT_OF_SERVICE','RETIRED')),
  commissioned_at date,
  retired_at date,
  created_at timestamptz not null default now(),
  row_version bigint not null default 1,
  unique (organization_id, id),
  unique (property_id, code),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, unit_type_id) references unit_type(organization_id, id),
  foreign key (organization_id, zone_id) references zone(organization_id, id)
);

create table resource (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  zone_id uuid,
  code text not null,
  name text not null,
  resource_type text not null,
  capacity integer not null check (capacity > 0),
  booking_mode text not null check (booking_mode in ('NONE','SLOT','DURATION','EXCLUSIVE','CAPACITY')),
  buffer_before interval not null default interval '0 minutes',
  buffer_after interval not null default interval '0 minutes',
  active boolean not null default true,
  row_version bigint not null default 1,
  unique (organization_id, id),
  unique (property_id, code),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, zone_id) references zone(organization_id, id)
);

create table asset (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  unit_id uuid,
  resource_id uuid,
  zone_id uuid,
  name text not null,
  asset_type text not null,
  manufacturer text,
  model text,
  serial_number text,
  installed_at date,
  purchase_date date,
  warranty_until date,
  lifecycle_status text not null check (lifecycle_status in ('PLANNED','ORDERED','INSTALLED','ACTIVE','DEGRADED','FAILED','RETIRED')),
  created_at timestamptz not null default now(),
  row_version bigint not null default 1,
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, unit_id) references unit(organization_id, id),
  foreign key (organization_id, resource_id) references resource(organization_id, id),
  foreign key (organization_id, zone_id) references zone(organization_id, id),
  check (num_nonnulls(unit_id, resource_id, zone_id) <= 1)
);

create table availability_block (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  unit_id uuid,
  resource_id uuid,
  start_at timestamptz not null,
  end_at timestamptz not null,
  reason_type text not null,
  reason_text text,
  source_incident_id uuid,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','ENDED','CANCELLED')),
  created_at timestamptz not null default now(),
  ended_at timestamptz,
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, unit_id) references unit(organization_id, id),
  foreign key (organization_id, resource_id) references resource(organization_id, id),
  check (end_at > start_at),
  check (num_nonnulls(unit_id, resource_id) = 1)
);

-- ================================================================
-- GUEST / RESERVATION / STAY
-- ================================================================

create table guest_profile (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  party_id uuid not null,
  preferred_language text,
  crm_status text not null default 'ACTIVE' check (crm_status in ('ACTIVE','BLOCKED','ARCHIVED')),
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  unique (organization_id, party_id),
  foreign key (organization_id, party_id) references party(organization_id, id)
);

create table channel (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  code text not null,
  name text not null,
  channel_type text not null,
  active boolean not null default true,
  unique (organization_id, id),
  unique (property_id, code),
  foreign key (organization_id, property_id) references property(organization_id, id)
);

create table reservation (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  channel_id uuid,
  primary_guest_id uuid,
  reference_code text not null,
  commercial_status text not null check (commercial_status in ('INQUIRY','HELD','CONFIRMED','CANCELLED','NO_SHOW')),
  booked_at timestamptz not null,
  currency char(3) not null,
  source_created_at timestamptz,
  source_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  row_version bigint not null default 1,
  unique (organization_id, id),
  unique (property_id, reference_code),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, channel_id) references channel(organization_id, id),
  foreign key (organization_id, primary_guest_id) references guest_profile(organization_id, id)
);

create table reservation_item (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  reservation_id uuid not null,
  unit_type_id uuid not null,
  assigned_unit_id uuid,
  arrival_date date not null,
  departure_date date not null,
  adults integer not null default 1 check (adults >= 0),
  children integer not null default 0 check (children >= 0),
  infants integer not null default 0 check (infants >= 0),
  pets integer not null default 0 check (pets >= 0),
  status text not null default 'ACTIVE' check (status in ('ACTIVE','CANCELLED')),
  row_version bigint not null default 1,
  unique (organization_id, id),
  foreign key (organization_id, reservation_id) references reservation(organization_id, id),
  foreign key (organization_id, unit_type_id) references unit_type(organization_id, id),
  foreign key (organization_id, assigned_unit_id) references unit(organization_id, id),
  check (departure_date > arrival_date)
);

create table commercial_policy_snapshot (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  reservation_id uuid not null,
  reservation_item_id uuid,
  version_no integer not null,
  currency char(3) not null,
  quoted_total numeric(14,2),
  cancellation_policy jsonb not null default '{}'::jsonb,
  pricing_breakdown jsonb not null default '{}'::jsonb,
  deposit_terms jsonb not null default '{}'::jsonb,
  source_reference text,
  effective_at timestamptz not null,
  supersedes_snapshot_id uuid,
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  unique (reservation_id, version_no),
  foreign key (organization_id, reservation_id) references reservation(organization_id, id),
  foreign key (organization_id, reservation_item_id) references reservation_item(organization_id, id),
  foreign key (organization_id, supersedes_snapshot_id) references commercial_policy_snapshot(organization_id, id)
);

create table stay (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  reservation_item_id uuid not null,
  primary_guest_id uuid,
  status text not null check (status in ('EXPECTED','CHECKED_IN','CHECKED_OUT','CANCELLED')),
  actual_checkin_at timestamptz,
  actual_checkout_at timestamptz,
  guest_count_actual integer check (guest_count_actual is null or guest_count_actual >= 0),
  created_at timestamptz not null default now(),
  row_version bigint not null default 1,
  unique (organization_id, id),
  foreign key (organization_id, reservation_item_id) references reservation_item(organization_id, id),
  foreign key (organization_id, primary_guest_id) references guest_profile(organization_id, id)
);

create table stay_segment (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  stay_id uuid not null,
  unit_id uuid not null,
  start_at timestamptz not null,
  end_at timestamptz not null,
  status text not null default 'ACTIVE' check (status in ('ACTIVE','CANCELLED')),
  reason text,
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  foreign key (organization_id, stay_id) references stay(organization_id, id),
  foreign key (organization_id, unit_id) references unit(organization_id, id),
  check (end_at > start_at)
);

alter table stay_segment
  add constraint ex_stay_segment_no_overlap
  exclude using gist (
    organization_id with =,
    unit_id with =,
    tstzrange(start_at, end_at, '[)') with &&
  ) where (status = 'ACTIVE');

create table stay_guest (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  stay_id uuid not null,
  guest_profile_id uuid,
  role text not null check (role in ('PRIMARY','ADULT','CHILD','OTHER')),
  unique (organization_id, id),
  foreign key (organization_id, stay_id) references stay(organization_id, id),
  foreign key (organization_id, guest_profile_id) references guest_profile(organization_id, id)
);

-- ================================================================
-- FOLIO / COMMERCE
-- ================================================================

create table folio (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  reservation_id uuid not null,
  stay_id uuid,
  currency char(3) not null,
  status text not null check (status in ('OPEN','CLOSED','VOID')),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  row_version bigint not null default 1,
  unique (organization_id, id),
  foreign key (organization_id, reservation_id) references reservation(organization_id, id),
  foreign key (organization_id, stay_id) references stay(organization_id, id)
);

create table charge (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  folio_id uuid not null,
  charge_type text not null check (charge_type in ('ACCOMMODATION','SERVICE','FEE','TAX','DISCOUNT','DAMAGE','CANCELLATION','OTHER')),
  description text not null,
  quantity numeric(12,3) not null default 1,
  unit_price numeric(14,2) not null,
  gross_amount numeric(14,2) not null,
  net_amount numeric(14,2),
  tax_amount numeric(14,2),
  recognized_at timestamptz,
  status text not null check (status in ('PENDING','POSTED','RECOGNIZED','REVERSED')),
  reverses_charge_id uuid,
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  foreign key (organization_id, folio_id) references folio(organization_id, id),
  foreign key (organization_id, reverses_charge_id) references charge(organization_id, id)
);

create table payment (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  folio_id uuid not null,
  payer_party_id uuid,
  method text not null,
  provider text,
  amount numeric(14,2) not null check (amount >= 0),
  currency char(3) not null,
  status text not null check (status in ('PENDING','CONFIRMED','FAILED','REFUNDED','PARTIALLY_REFUNDED')),
  paid_at timestamptz,
  external_reference text,
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  foreign key (organization_id, folio_id) references folio(organization_id, id),
  foreign key (organization_id, payer_party_id) references party(organization_id, id)
);

create table payment_allocation (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  payment_id uuid not null,
  charge_id uuid not null,
  amount numeric(14,2) not null check (amount > 0),
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  unique (payment_id, charge_id),
  foreign key (organization_id, payment_id) references payment(organization_id, id),
  foreign key (organization_id, charge_id) references charge(organization_id, id)
);

create table refund (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  payment_id uuid not null,
  amount numeric(14,2) not null check (amount > 0),
  currency char(3) not null,
  status text not null check (status in ('PENDING','CONFIRMED','FAILED')),
  refunded_at timestamptz,
  external_reference text,
  reason text,
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  foreign key (organization_id, payment_id) references payment(organization_id, id)
);

-- ================================================================
-- EXPERIENCE / RESOURCE CAPACITY
-- ================================================================

create table service (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  code text not null,
  name text not null,
  service_type text not null,
  pricing_mode text not null,
  base_price numeric(14,2),
  requires_booking boolean not null default false,
  requires_resource boolean not null default false,
  active boolean not null default true,
  row_version bigint not null default 1,
  unique (organization_id, id),
  unique (property_id, code),
  foreign key (organization_id, property_id) references property(organization_id, id)
);

create table service_booking (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  service_id uuid not null,
  stay_id uuid,
  reservation_id uuid,
  guest_profile_id uuid,
  requested_start_at timestamptz,
  requested_end_at timestamptz,
  status text not null check (status in ('REQUESTED','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW')),
  created_at timestamptz not null default now(),
  row_version bigint not null default 1,
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, service_id) references service(organization_id, id),
  foreign key (organization_id, stay_id) references stay(organization_id, id),
  foreign key (organization_id, reservation_id) references reservation(organization_id, id),
  foreign key (organization_id, guest_profile_id) references guest_profile(organization_id, id),
  check (num_nonnulls(stay_id, reservation_id, guest_profile_id) >= 1)
);

create table service_execution (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  service_booking_id uuid not null,
  actual_start_at timestamptz,
  actual_end_at timestamptz,
  status text not null check (status in ('STARTED','COMPLETED','CANCELLED','NO_SHOW')),
  notes text,
  unique (organization_id, id),
  foreign key (organization_id, service_booking_id) references service_booking(organization_id, id),
  check (actual_end_at is null or actual_start_at is null or actual_end_at > actual_start_at)
);

create table resource_reservation (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  resource_id uuid not null,
  service_booking_id uuid,
  start_at timestamptz not null,
  end_at timestamptz not null,
  effective_start_at timestamptz not null,
  effective_end_at timestamptz not null,
  capacity_used integer not null default 1 check (capacity_used > 0),
  exclusive_booking boolean not null default false,
  status text not null check (status in ('HELD','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','EXPIRED')),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  foreign key (organization_id, resource_id) references resource(organization_id, id),
  foreign key (organization_id, service_booking_id) references service_booking(organization_id, id),
  check (end_at > start_at),
  check (effective_end_at > effective_start_at)
);

alter table resource_reservation
  add constraint ex_exclusive_resource_no_overlap
  exclude using gist (
    organization_id with =,
    resource_id with =,
    tstzrange(effective_start_at, effective_end_at, '[)') with &&
  ) where (exclusive_booking = true and status in ('HELD','CONFIRMED','IN_PROGRESS'));

-- ================================================================
-- OPERATIONS / MAINTENANCE
-- ================================================================

create table incident (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  unit_id uuid,
  resource_id uuid,
  asset_id uuid,
  severity text not null check (severity in ('LOW','MEDIUM','HIGH','CRITICAL')),
  status text not null check (status in ('OPEN','TRIAGED','IN_REPAIR','RESOLVED','CLOSED')),
  title text not null,
  description text,
  guest_impact boolean not null default false,
  safety_related boolean not null default false,
  reported_at timestamptz not null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  row_version bigint not null default 1,
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, unit_id) references unit(organization_id, id),
  foreign key (organization_id, resource_id) references resource(organization_id, id),
  foreign key (organization_id, asset_id) references asset(organization_id, id)
);

alter table availability_block
  add foreign key (organization_id, source_incident_id) references incident(organization_id, id);

create table turnover (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  unit_id uuid not null,
  previous_stay_id uuid,
  next_stay_id uuid,
  available_from timestamptz,
  ready_deadline timestamptz,
  status text not null check (status in ('PENDING','IN_PROGRESS','READY','BLOCKED','CANCELLED')),
  priority text not null default 'NORMAL',
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  row_version bigint not null default 1,
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, unit_id) references unit(organization_id, id),
  foreign key (organization_id, previous_stay_id) references stay(organization_id, id),
  foreign key (organization_id, next_stay_id) references stay(organization_id, id)
);

create table task (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  turnover_id uuid,
  incident_id uuid,
  assignee_user_id uuid,
  task_type text not null,
  title text not null,
  description text,
  priority text not null default 'NORMAL',
  status text not null check (status in ('OPEN','IN_PROGRESS','DONE','BLOCKED','CANCELLED')),
  due_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  row_version bigint not null default 1,
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, turnover_id) references turnover(organization_id, id),
  foreign key (organization_id, incident_id) references incident(organization_id, id),
  foreign key (organization_id, assignee_user_id) references user_account(organization_id, id)
);

create table work_log (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  task_id uuid not null,
  performed_by_user_id uuid,
  started_at timestamptz,
  ended_at timestamptz,
  minutes integer check (minutes is null or minutes >= 0),
  notes text,
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  foreign key (organization_id, task_id) references task(organization_id, id),
  foreign key (organization_id, performed_by_user_id) references user_account(organization_id, id),
  check (ended_at is null or started_at is null or ended_at >= started_at)
);

create table work_order (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  incident_id uuid,
  asset_id uuid,
  contractor_party_id uuid,
  status text not null check (status in ('DRAFT','REQUESTED','SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED')),
  requested_at timestamptz,
  scheduled_at timestamptz,
  completed_at timestamptz,
  estimated_cost numeric(14,2),
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, incident_id) references incident(organization_id, id),
  foreign key (organization_id, asset_id) references asset(organization_id, id),
  foreign key (organization_id, contractor_party_id) references party(organization_id, id)
);

create table conflict_case (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  availability_block_id uuid,
  reservation_item_id uuid,
  stay_id uuid,
  severity text not null check (severity in ('LOW','MEDIUM','HIGH','CRITICAL')),
  reason text not null,
  status text not null check (status in ('OPEN','IN_REVIEW','RESOLVED','CANCELLED')),
  resolution_type text,
  resolved_by_user_id uuid,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, availability_block_id) references availability_block(organization_id, id),
  foreign key (organization_id, reservation_item_id) references reservation_item(organization_id, id),
  foreign key (organization_id, stay_id) references stay(organization_id, id),
  foreign key (organization_id, resolved_by_user_id) references user_account(organization_id, id)
);

-- ================================================================
-- FINANCIAL TRUTH
-- ================================================================

create table financial_period (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid,
  period_start date not null,
  period_end date not null,
  status text not null check (status in ('OPEN','SOFT_CLOSED','HARD_CLOSED')),
  closed_at timestamptz,
  closed_by_user_id uuid,
  unique (organization_id, id),
  unique (organization_id, property_id, period_start, period_end),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, closed_by_user_id) references user_account(organization_id, id),
  check (period_end >= period_start)
);

create table money_account (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid,
  name text not null,
  account_type text not null check (account_type in ('BANK','CASH','PAYMENT_PROVIDER_CLEARING','OTA_CLEARING','OWNER_FUNDS','OPERATOR_FUNDS','INTERNAL_CLEARING','OTHER')),
  currency char(3) not null,
  active boolean not null default true,
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id)
);

create table cash_movement (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  from_money_account_id uuid,
  to_money_account_id uuid,
  amount numeric(14,2) not null check (amount > 0),
  currency char(3) not null,
  occurred_at timestamptz not null,
  external_reference text,
  source_fingerprint text,
  status text not null check (status in ('IMPORTED','VERIFIED','REVERSED','IGNORED')),
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  foreign key (organization_id, from_money_account_id) references money_account(organization_id, id),
  foreign key (organization_id, to_money_account_id) references money_account(organization_id, id),
  check (num_nonnulls(from_money_account_id, to_money_account_id) >= 1),
  check (from_money_account_id is null or to_money_account_id is null or from_money_account_id <> to_money_account_id)
);

create table financial_document (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  document_type text not null,
  document_number text,
  issuer_party_id uuid,
  recipient_party_id uuid,
  issue_date date,
  service_date date,
  due_date date,
  currency char(3) not null,
  gross_total numeric(14,2) not null,
  net_total numeric(14,2),
  tax_total numeric(14,2),
  status text not null check (status in ('DRAFT','VERIFIED','POSTED','CORRECTED')),
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  foreign key (organization_id, issuer_party_id) references party(organization_id, id),
  foreign key (organization_id, recipient_party_id) references party(organization_id, id)
);

create table financial_document_line (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  financial_document_id uuid not null,
  line_no integer,
  description text not null,
  quantity numeric(12,3),
  gross_amount numeric(14,2) not null,
  net_amount numeric(14,2),
  tax_amount numeric(14,2),
  unique (organization_id, id),
  foreign key (organization_id, financial_document_id) references financial_document(organization_id, id)
);

create table investment_project (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid not null,
  name text not null,
  status text not null check (status in ('PLANNED','APPROVED','IN_PROGRESS','COMPLETED','CANCELLED')),
  budget numeric(14,2),
  planned_start date,
  actual_start date,
  planned_end date,
  actual_end date,
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id)
);

create table cost_center (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid,
  code text not null,
  name text not null,
  active boolean not null default true,
  unique (organization_id, id),
  unique (organization_id, code),
  foreign key (organization_id, property_id) references property(organization_id, id)
);

create table economic_event (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid,
  financial_period_id uuid,
  event_type text not null check (event_type in ('REVENUE','OPEX','CAPEX','OTA_COMMISSION','PAYMENT_FEE','REFUND','TAX','OWNER_CONTRIBUTION','OWNER_WITHDRAWAL','TRANSFER','SETTLEMENT','WRITE_OFF','ROUNDING','ADJUSTMENT')),
  economic_date date not null,
  amount numeric(14,2) not null check (amount >= 0),
  currency char(3) not null,
  source_document_line_id uuid,
  source_charge_id uuid,
  reverses_event_id uuid,
  status text not null check (status in ('DRAFT','REVIEWED','POSTED','REVERSED')),
  posted_at timestamptz,
  posted_by_user_id uuid,
  created_at timestamptz not null default now(),
  row_version bigint not null default 1,
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, financial_period_id) references financial_period(organization_id, id),
  foreign key (organization_id, source_document_line_id) references financial_document_line(organization_id, id),
  foreign key (organization_id, source_charge_id) references charge(organization_id, id),
  foreign key (organization_id, reverses_event_id) references economic_event(organization_id, id),
  foreign key (organization_id, posted_by_user_id) references user_account(organization_id, id)
);

create table allocation (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  economic_event_id uuid not null,
  amount numeric(14,2) not null check (amount >= 0),
  property_id uuid,
  unit_id uuid,
  stay_id uuid,
  resource_id uuid,
  asset_id uuid,
  service_id uuid,
  channel_id uuid,
  investment_project_id uuid,
  cost_center_id uuid,
  paid_by_party_id uuid,
  economic_bearer_party_id uuid,
  allocation_type text not null check (allocation_type in ('DIRECT','SHARED','OVERHEAD','NON_BUSINESS')),
  classification text not null check (classification in ('REVENUE','OPEX','CAPEX','NON_BUSINESS','OTHER')),
  confidence text not null check (confidence in ('VERIFIED','SYSTEM_DERIVED','ESTIMATED','MANUAL','UNKNOWN')),
  allocation_method text,
  rationale text,
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  foreign key (organization_id, economic_event_id) references economic_event(organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, unit_id) references unit(organization_id, id),
  foreign key (organization_id, stay_id) references stay(organization_id, id),
  foreign key (organization_id, resource_id) references resource(organization_id, id),
  foreign key (organization_id, asset_id) references asset(organization_id, id),
  foreign key (organization_id, service_id) references service(organization_id, id),
  foreign key (organization_id, channel_id) references channel(organization_id, id),
  foreign key (organization_id, investment_project_id) references investment_project(organization_id, id),
  foreign key (organization_id, cost_center_id) references cost_center(organization_id, id),
  foreign key (organization_id, paid_by_party_id) references party(organization_id, id),
  foreign key (organization_id, economic_bearer_party_id) references party(organization_id, id),
  check (confidence not in ('ESTIMATED','MANUAL') or rationale is not null)
);

create table settlement_entry (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  source_economic_event_id uuid,
  source_allocation_id uuid,
  creditor_party_id uuid not null,
  debtor_party_id uuid not null,
  amount numeric(14,2) not null check (amount > 0),
  currency char(3) not null,
  status text not null check (status in ('OPEN','PARTIALLY_SETTLED','SETTLED','REVERSED')),
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  foreign key (organization_id, source_economic_event_id) references economic_event(organization_id, id),
  foreign key (organization_id, source_allocation_id) references allocation(organization_id, id),
  foreign key (organization_id, creditor_party_id) references party(organization_id, id),
  foreign key (organization_id, debtor_party_id) references party(organization_id, id),
  check (creditor_party_id <> debtor_party_id),
  check (num_nonnulls(source_economic_event_id, source_allocation_id) >= 1)
);

create table settlement_application (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  settlement_entry_id uuid not null,
  cash_movement_id uuid,
  amount numeric(14,2) not null check (amount > 0),
  applied_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  foreign key (organization_id, settlement_entry_id) references settlement_entry(organization_id, id),
  foreign key (organization_id, cash_movement_id) references cash_movement(organization_id, id)
);

-- ================================================================
-- AUDIT / DOMAIN EVENTS / APPROVALS
-- ================================================================

create table domain_event (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid,
  event_type text not null,
  event_version integer not null default 1 check (event_version > 0),
  aggregate_type text not null,
  aggregate_id uuid not null,
  aggregate_version bigint,
  occurred_at timestamptz not null,
  recorded_at timestamptz not null default now(),
  correlation_id uuid,
  causation_id uuid,
  actor_type text,
  actor_id uuid,
  payload jsonb not null default '{}'::jsonb,
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id)
);

create table outbox_event (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  domain_event_id uuid not null,
  status text not null default 'PENDING' check (status in ('PENDING','PUBLISHING','PUBLISHED','FAILED_RETRYABLE','FAILED_FINAL')),
  available_at timestamptz not null default now(),
  published_at timestamptz,
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  created_at timestamptz not null default now(),
  unique (organization_id, id),
  unique (domain_event_id),
  foreign key (organization_id, domain_event_id) references domain_event(organization_id, id)
);

create table audit_event (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid,
  actor_type text not null,
  actor_id uuid,
  entity_type text not null,
  entity_id uuid not null,
  action text not null,
  occurred_at timestamptz not null default now(),
  request_id uuid,
  source text,
  changes jsonb not null default '{}'::jsonb,
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id)
);

create table approval_request (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid,
  subject_type text not null,
  subject_id uuid not null,
  subject_version bigint,
  policy_code text not null,
  policy_version integer not null,
  requested_by_user_id uuid not null,
  status text not null check (status in ('PENDING','APPROVED','REJECTED','EXPIRED','CANCELLED')),
  requested_at timestamptz not null default now(),
  expires_at timestamptz,
  risk_context jsonb not null default '{}'::jsonb,
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id),
  foreign key (organization_id, requested_by_user_id) references user_account(organization_id, id)
);

create table approval_decision (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  approval_request_id uuid not null,
  approver_user_id uuid not null,
  decision text not null check (decision in ('APPROVE','REJECT')),
  reason text,
  decided_at timestamptz not null default now(),
  unique (organization_id, id),
  foreign key (organization_id, approval_request_id) references approval_request(organization_id, id),
  foreign key (organization_id, approver_user_id) references user_account(organization_id, id)
);

create table data_quality_issue (
  id uuid primary key,
  organization_id uuid not null references organization(id),
  property_id uuid,
  issue_type text not null,
  severity text not null check (severity in ('INFO','LOW','MEDIUM','HIGH','CRITICAL')),
  subject_type text,
  subject_id uuid,
  status text not null check (status in ('OPEN','ACKNOWLEDGED','RESOLVED','IGNORED')),
  details jsonb not null default '{}'::jsonb,
  detected_at timestamptz not null default now(),
  resolved_at timestamptz,
  unique (organization_id, id),
  foreign key (organization_id, property_id) references property(organization_id, id)
);

-- ================================================================
-- P0 FINANCIAL GUARDS — proof implementation
-- ================================================================

create or replace function osg_guard_posted_economic_event()
returns trigger language plpgsql as $$
begin
  if old.status = 'POSTED' then
    if new.amount is distinct from old.amount
       or new.currency is distinct from old.currency
       or new.economic_date is distinct from old.economic_date
       or new.event_type is distinct from old.event_type
       or new.organization_id is distinct from old.organization_id
       or new.property_id is distinct from old.property_id then
      raise exception 'OSG_POSTED_EVENT_IMMUTABLE';
    end if;
  end if;
  return new;
end $$;

create trigger trg_guard_posted_economic_event
before update on economic_event
for each row execute function osg_guard_posted_economic_event();

create or replace function osg_guard_allocation_of_posted_event()
returns trigger language plpgsql as $$
declare
  v_event_id uuid;
  v_status text;
begin
  v_event_id := coalesce(old.economic_event_id, new.economic_event_id);
  select status into v_status from economic_event where id = v_event_id;
  if v_status = 'POSTED' then
    raise exception 'OSG_POSTED_ALLOCATION_IMMUTABLE';
  end if;
  return coalesce(new, old);
end $$;

create trigger trg_guard_allocation_of_posted_event
before update or delete on allocation
for each row execute function osg_guard_allocation_of_posted_event();

create or replace function osg_assert_economic_event_balanced(p_event_id uuid)
returns void language plpgsql as $$
declare
  v_amount numeric(14,2);
  v_status text;
  v_sum numeric(14,2);
begin
  select amount, status into v_amount, v_status
  from economic_event where id = p_event_id for update;

  if v_status = 'POSTED' then
    select coalesce(sum(amount),0) into v_sum
    from allocation where economic_event_id = p_event_id;
    if v_sum <> v_amount then
      raise exception 'OSG_ALLOCATION_NOT_BALANCED event=% expected=% actual=%', p_event_id, v_amount, v_sum;
    end if;
  end if;
end $$;

-- Application posting transaction MUST call osg_assert_economic_event_balanced()
-- after switching to POSTED and before COMMIT, or replace with a reviewed
-- deferred constraint-trigger implementation after executable P0 proof.

-- ================================================================
-- REQUIRED INDEXES — initial set
-- ================================================================

create index idx_reservation_property_dates on reservation(property_id, booked_at);
create index idx_reservation_item_dates on reservation_item(arrival_date, departure_date);
create index idx_stay_status on stay(organization_id, status);
create index idx_stay_segment_unit_time on stay_segment(unit_id, start_at, end_at);
create index idx_resource_reservation_time on resource_reservation(resource_id, effective_start_at, effective_end_at);
create index idx_turnover_deadline on turnover(property_id, status, ready_deadline);
create index idx_task_due on task(property_id, status, due_at);
create index idx_incident_open on incident(property_id, status, severity);
create index idx_cash_movement_date on cash_movement(organization_id, occurred_at);
create index idx_economic_event_date on economic_event(organization_id, economic_date, status);
create index idx_allocation_event on allocation(economic_event_id);
create index idx_settlement_open on settlement_entry(organization_id, status);
create index idx_outbox_pending on outbox_event(status, available_at) where status in ('PENDING','FAILED_RETRYABLE');
create index idx_dq_open on data_quality_issue(organization_id, status, severity);

-- ================================================================
-- STILL REQUIRED BEFORE v1.0 FINAL
-- ================================================================
-- 1. Execute P0 concurrency and tenant isolation tests.
-- 2. Add application/RLS tenant scope proof; composite FKs already protect many links.
-- 3. Implement capacity>1 Resource transaction/lock service.
-- 4. Implement payment allocation conservation checks.
-- 5. Implement settlement over-application guard.
-- 6. Review commercial snapshot JSON fields against first real PMS payload.
-- 7. Promote only through versioned migrations after Schema v1.0 FINAL.
